services:
  v6tprouter:
    image: v6tprouter:latest
    container_name: v6tprouter
    hostname: v6tprouter
    restart: on-failure:3
    privileged: true
    networks:
      - ip6
      - ip6br1
      - ip6br2
      - ip6br3
    environment:
      - TZ=Asia/Shanghai
      # - PREFIX_LEN=56
      # - RUST_LOG=debug
    sysctls:
      - "net.ipv6.conf.all.forwarding=1"
      - "net.ipv6.conf.all.proxy_ndp=1"
      - "net.ipv6.conf.all.accept_ra=2"
      - "net.ipv6.conf.default.forwarding=1"
      - "net.ipv6.conf.default.proxy_ndp=1"
      - "net.ipv6.conf.default.accept_ra=2"

networks:
  ip6:
    driver: macvlan
    enable_ipv4: false
    enable_ipv6: true
    driver_opts:
      parent: "eno1"
  ip6br1:
    enable_ipv4: false
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: "ip6br1"
      com.docker.network.container_iface_prefix: "ip6br1eth"
  ip6br2:
    enable_ipv4: false
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: "ip6br2"
      com.docker.network.container_iface_prefix: "ip6br2eth"
  ip6br3:
    enable_ipv4: false
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: "ip6br3"
      com.docker.network.container_iface_prefix: "ip6br3eth"