# 链式调用时的最大宽度
chain_width = 120
array_width = 120
max_width = 120
struct_lit_width = 120
fn_call_width = 120
newline_style = "Unix"
tab_spaces = 2
comment_width = 120
edition = "2024"
style_edition = "2024"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Max"
use_field_init_shorthand = true